import { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import { Calculator, RefreshCw, ShieldAlert, TrendingDown, WalletCards } from 'lucide-react';
import './FinancialImpactPage.css';

const API = '/api/v1';
const money = (value) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(value || 0);
function Empty() { return <div className="empty-state"><Calculator size={20} /><strong>No evaluation data available</strong><span>Generate or load held-out model metrics to calculate simulated impact.</span></div>; }

export default function FinancialImpactPage() {
  const [metrics, setMetrics] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [falseNegativeCost, setFalseNegativeCost] = useState(450); const [falsePositiveCost, setFalsePositiveCost] = useState(15);
  useEffect(() => { axios.get(`${API}/model/metrics`).then((response) => { setMetrics(response.data); const costs = response.data.cost_analysis || {}; if (costs.cost_per_false_negative_usd != null) setFalseNegativeCost(costs.cost_per_false_negative_usd); if (costs.cost_per_false_positive_usd != null) setFalsePositiveCost(costs.cost_per_false_positive_usd); }).catch(() => setError('Model evaluation data is unavailable.')).finally(() => setLoading(false)); }, []);
  const impact = useMemo(() => { if (!metrics) return null; const c = metrics.confusion_matrix || {}; const fp = Number(c.false_positives || 0); const fn = Number(c.false_negatives || 0); const tp = Number(c.true_positives || 0); const tn = Number(c.true_negatives || 0); const fraudTotal = Number(metrics.test_fraud_count || fn + tp); const legitTotal = Number(metrics.test_legit_count || tn + fp); const avoided = Math.max(0, fraudTotal * Number(metrics.cost_analysis?.cost_per_false_negative_usd ?? falseNegativeCost) - fn * falseNegativeCost); const fpCost = fp * falsePositiveCost; return { fp, fn, tp, tn, fraudTotal, legitTotal, avoided, fpCost, net: avoided - fpCost, reviewed: Number(metrics.n_heldout_test_samples || fraudTotal + legitTotal), avgLegit: Number(metrics.cost_analysis?.average_legitimate_transaction_value_usd || 0), avgFraud: Number(metrics.cost_analysis?.average_fraudulent_transaction_value_usd || 0) }; }, [metrics, falseNegativeCost, falsePositiveCost]);
  if (loading) return <div className="loading-state"><RefreshCw className="spin" size={18} />Loading financial impact from held-out evaluation...</div>;
  if (error || !impact) return <><div className="page-intro"><div><div className="eyebrow">Financial impact / Simulation</div><h1>Financial impact</h1><p>Reproducible estimates based on the held-out test dataset.</p></div></div>{error ? <div className="state-banner">{error}</div> : <Empty />}</>;
  const withoutAi = [{ label: 'Transactions reviewed', value: impact.reviewed }, { label: 'Fraudulent transactions caught', value: 0 }, { label: 'Legitimate incorrectly blocked', value: 0 }, { label: 'Estimated financial impact', value: -impact.fraudTotal * falseNegativeCost }];
  const withAi = [{ label: 'Transactions reviewed', value: impact.reviewed }, { label: 'Fraudulent transactions caught', value: impact.tp }, { label: 'Legitimate incorrectly blocked', value: impact.fp }, { label: 'Estimated financial impact', value: impact.net }];
  return <><div className="page-intro"><div><div className="eyebrow">Financial impact / Simulation</div><h1>Estimated financial impact</h1><p>Based on test dataset results. These are simulated estimates, not realized merchant savings.</p></div><button className="secondary-button" onClick={() => window.location.reload()}><RefreshCw size={15} />Refresh</button></div><div className="assumption-banner"><div><strong>Configurable assumptions</strong><span>Change the cost model to reproduce the estimate. Values are not claims of real financial savings.</span></div><label>Loss per missed fraud ($)<input type="number" min="0" step="1" value={falseNegativeCost} onChange={(event) => setFalseNegativeCost(Number(event.target.value))} /></label><label>Cost per false positive ($)<input type="number" min="0" step="1" value={falsePositiveCost} onChange={(event) => setFalsePositiveCost(Number(event.target.value))} /></label></div><div className="impact-grid"><article><span className="impact-icon red"><ShieldAlert size={18} /></span><small>False positives</small><strong>{impact.fp}</strong><em>Held-out test set</em></article><article><span className="impact-icon orange"><TrendingDown size={18} /></span><small>False negatives</small><strong>{impact.fn}</strong><em>Held-out test set</em></article><article><span className="impact-icon blue"><WalletCards size={18} /></span><small>Average legitimate value</small><strong>{money(impact.avgLegit)}</strong><em>Based on test dataset</em></article><article><span className="impact-icon purple"><WalletCards size={18} /></span><small>Average fraudulent value</small><strong>{money(impact.avgFraud)}</strong><em>Based on test dataset</em></article><article><small>Estimated false-positive cost</small><strong>{money(impact.fpCost)}</strong><em>Simulated assumption</em></article><article><small>Estimated fraud loss avoided</small><strong>{money(impact.avoided)}</strong><em>Simulated, not realized</em></article><article className="net"><small>Estimated net benefit</small><strong>{money(impact.net)}</strong><em>Based on test dataset</em></article></div><section className="scenario-panel"><div className="panel-heading"><div><h3>Scenario comparison</h3><p>Without AI vs With RazorGuard - reproducible held-out test-set comparison</p></div></div><div className="scenario-grid"><Scenario title="Without AI" tone="without" rows={withoutAi} /><Scenario title="With RazorGuard" tone="with" rows={withAi} /></div></section><div className="impact-footnote">Method: fraud loss baseline = held-out fraud count x missed-fraud cost. RazorGuard estimate = baseline loss avoided by caught frauds minus false-positive cost. All figures are estimated and simulated from the test dataset.</div></>;
}
function Scenario({ title, tone, rows }) { return <article className={`scenario-card ${tone}`}><h3>{title}</h3>{rows.map((row) => <div key={row.label}><span>{row.label}</span><strong>{typeof row.value === 'number' && row.label.includes('impact') ? money(row.value) : row.value.toLocaleString()}</strong></div>)}</article>; }
