"""Contract tests for the Phase 12 transaction investigation workflow."""

from pathlib import Path


ROOT = Path(__file__).parents[1]
COMPONENT = (ROOT / "frontend" / "src" / "components" / "InvestigationPage.jsx").read_text(encoding="utf-8")
STYLES = (ROOT / "frontend" / "src" / "components" / "InvestigationPage.css").read_text(encoding="utf-8")
APP = (ROOT / "frontend" / "src" / "App.jsx").read_text(encoding="utf-8")


def test_phase12_investigation_is_wired_from_transaction_selection():
    assert "InvestigationPage" in APP
    assert "setSelectedId" in APP
    assert "setPage('investigation')" in APP
    assert "onClick={() => open(item.transaction_id)}" in APP


def test_phase12_loads_detail_and_complete_audit_timeline_from_backend():
    assert "axios.get(`${API}/transactions/${id}`)" in COMPONENT
    assert "axios.get(`${API}/audit?transaction_id=" in COMPONENT
    assert "Complete audit timeline" in COMPONENT
    assert "Every decision and workflow action is recorded by the backend" in COMPONENT


def test_phase12_displays_risk_evidence_and_ai_explanation():
    for label in (
        "Transaction information",
        "Final decision",
        "Fraud probability",
        "Risk score",
        "Why was this transaction flagged?",
        "Top SHAP risk factors from the backend explanation service",
        "AI Risk Analyst Explanation",
        "Generated by the backend GenAI explanation service",
    ):
        assert label in COMPONENT
    assert "detail.llm_explanation.summary_headline" in COMPONENT
    assert "detail.llm_explanation.why_flagged" in COMPONENT
    assert "factor.impact_direction" in COMPONENT


def test_phase12_actions_are_simulated_and_audit_logged():
    assert "Simulated merchant workflow action" in COMPONENT
    assert "No payment was processed" in COMPONENT
    assert "axios.post(`${API}/verification/${encodeURIComponent(id)}`" in COMPONENT
    for action in ("OVERRIDE_APPROVE", "CONFIRM_LEGIT", "OVERRIDE_BLOCK"):
        assert action in COMPONENT
    assert "recorded in the audit trail" in COMPONENT


def test_phase12_has_gauge_loading_error_and_empty_states():
    assert "function RiskGauge" in COMPONENT
    assert "gauge-needle" in COMPONENT
    assert "Loading investigation" in COMPONENT
    assert "Transaction investigation data is unavailable" in COMPONENT
    assert "No transaction selected" in COMPONENT
    assert "No SHAP factors returned" in COMPONENT
    assert "No audit events available" in COMPONENT
    assert ".risk-gauge" in STYLES
    assert ".timeline" in STYLES
    assert ".workflow-actions" in STYLES
