"""
RazorGuard AI - Controlled Hackathon Demo Scenarios

Defines 4 reproducible, production-grounded demo scenarios with fixed parameters:
- SCENARIO 1: Normal returning customer -> LOW RISK -> APPROVE
- SCENARIO 2: New customer + unusual amount -> MEDIUM RISK -> REVIEW
- SCENARIO 3: Multiple payment attempts + device reuse + velocity -> HIGH RISK -> BLOCK
- SCENARIO 4: Known legitimate customer with high-value purchase -> LOW RISK -> APPROVE (High Amount != Fraud)

Zero model tampering: The outputs are naturally generated by the trained ML models and policy rules.
"""

from typing import Dict, Any, List, Optional
import copy

DEMO_SCENARIOS: Dict[str, Dict[str, Any]] = {
    "scenario_1": {
        "id": "scenario_1",
        "title": "Scenario 1: Normal Returning Customer",
        "badge": "LOW RISK / APPROVE",
        "expected_risk_level": "LOW",
        "expected_decision": "APPROVE",
        "headline": "Established account with domestic credentials and recurring transaction history",
        "demonstration_focus": "Demonstrates baseline approval with strong protective loyalty features (account age, repeat order frequency, zero chargebacks).",
        "transaction": {
            "transaction_id": "TXN_DEMO_SCENARIO_1",
            "customer_id": "CUST_LOYAL_4821",
            "merchant_id": "MERCH_ECOMM_01",
            "amount": 42.50,
            "currency": "USD",
            "merchant_category": "retail",
            "payment_method": "credit_card",
            "country": "US",
            "account_age_days": 365,
            "customer_transaction_count": 48,
            "transactions_last_24h": 1,
            "transactions_last_7d": 4,
            "average_transaction_amount": 45.0,
            "payment_attempts": 1,
            "failed_payment_count": 0,
            "previous_fraud_count": 0,
            "previous_chargeback_count": 0,
            "unique_devices": 1,
            "unique_ips": 1,
            "billing_shipping_match": 1,
            "country_change": 0,
            "device_reuse_count": 1,
            "velocity_score": 5.0,
            "hour_of_day": 14,
            "day_of_week": 2,
        },
    },
    "scenario_2": {
        "id": "scenario_2",
        "title": "Scenario 2: New Customer + Unusual Amount",
        "badge": "MEDIUM RISK / REVIEW",
        "expected_risk_level": "MEDIUM",
        "expected_decision": "REVIEW",
        "headline": "Recent account with ticket size significantly higher than limited history",
        "demonstration_focus": "Demonstrates automated routing to the analyst review queue when risk is ambiguous without prematurely blocking the buyer.",
        "transaction": {
            "transaction_id": "TXN_DEMO_SCENARIO_2",
            "customer_id": "CUST_NEW_9012",
            "merchant_id": "MERCH_ELEC_09",
            "amount": 280.00,
            "currency": "USD",
            "merchant_category": "electronics",
            "payment_method": "credit_card",
            "country": "US",
            "account_age_days": 5,
            "customer_transaction_count": 2,
            "transactions_last_24h": 1,
            "transactions_last_7d": 1,
            "average_transaction_amount": 30.0,
            "payment_attempts": 1,
            "failed_payment_count": 0,
            "previous_fraud_count": 0,
            "previous_chargeback_count": 0,
            "unique_devices": 1,
            "unique_ips": 1,
            "billing_shipping_match": 1,
            "country_change": 0,
            "device_reuse_count": 1,
            "velocity_score": 15.0,
            "hour_of_day": 20,
            "day_of_week": 3,
        },
    },
    "scenario_3": {
        "id": "scenario_3",
        "title": "Scenario 3: Brute Force Retries & Device Reuse Attack",
        "badge": "HIGH RISK / BLOCK",
        "expected_risk_level": "HIGH",
        "expected_decision": "BLOCK",
        "headline": "Multiple failed card auths, device shared across 8 accounts, velocity spike",
        "demonstration_focus": "Demonstrates instant blocking by combined ML anomaly detection and hard deterministic security rules (brute-force defense).",
        "transaction": {
            "transaction_id": "TXN_DEMO_SCENARIO_3",
            "customer_id": "CUST_SUSPICIOUS_771",
            "merchant_id": "MERCH_LUX_04",
            "amount": 1250.00,
            "currency": "USD",
            "merchant_category": "luxury",
            "payment_method": "credit_card",
            "country": "US",
            "account_age_days": 12,
            "customer_transaction_count": 8,
            "transactions_last_24h": 9,
            "transactions_last_7d": 15,
            "average_transaction_amount": 85.0,
            "payment_attempts": 4,
            "failed_payment_count": 3,
            "previous_fraud_count": 1,
            "previous_chargeback_count": 1,
            "unique_devices": 5,
            "unique_ips": 4,
            "billing_shipping_match": 0,
            "country_change": 1,
            "device_reuse_count": 8,
            "velocity_score": 88.0,
            "hour_of_day": 3,
            "day_of_week": 6,
        },
    },
    "scenario_4": {
        "id": "scenario_4",
        "title": "Scenario 4: High-Value Purchase by Known VIP Customer",
        "badge": "SAFE VIP / APPROVE",
        "expected_risk_level": "LOW",
        "expected_decision": "APPROVE",
        "headline": "Large $2,450 purchase safely approved due to proven loyalty & verified identity",
        "demonstration_focus": "Demonstrates that high ticket size alone does NOT trigger false-positive blocks when outweighed by solid protective trust features.",
        "transaction": {
            "transaction_id": "TXN_DEMO_SCENARIO_4",
            "customer_id": "CUST_VIP_1099",
            "merchant_id": "MERCH_TRAVEL_02",
            "amount": 2450.00,
            "currency": "USD",
            "merchant_category": "travel",
            "payment_method": "credit_card",
            "country": "US",
            "account_age_days": 520,
            "customer_transaction_count": 110,
            "transactions_last_24h": 1,
            "transactions_last_7d": 3,
            "average_transaction_amount": 1800.0,
            "payment_attempts": 1,
            "failed_payment_count": 0,
            "previous_fraud_count": 0,
            "previous_chargeback_count": 0,
            "unique_devices": 1,
            "unique_ips": 1,
            "billing_shipping_match": 1,
            "country_change": 0,
            "device_reuse_count": 1,
            "velocity_score": 8.0,
            "hour_of_day": 11,
            "day_of_week": 1,
        },
    },
}


def get_all_scenarios_metadata() -> List[Dict[str, Any]]:
    """
    Returns list of demo scenarios with metadata for UI rendering.
    """
    results = []
    for key, item in DEMO_SCENARIOS.items():
        results.append({
            "id": item["id"],
            "title": item["title"],
            "badge": item["badge"],
            "expected_risk_level": item["expected_risk_level"],
            "expected_decision": item["expected_decision"],
            "headline": item["headline"],
            "demonstration_focus": item["demonstration_focus"],
            "amount": item["transaction"]["amount"],
            "currency": item["transaction"]["currency"],
            "customer_id": item["transaction"]["customer_id"],
            "merchant_category": item["transaction"]["merchant_category"],
        })
    return results


def get_scenario_by_id(scenario_id: str) -> Optional[Dict[str, Any]]:
    """
    Returns deepcopy of the requested scenario data.
    """
    scenario = DEMO_SCENARIOS.get(scenario_id)
    if scenario:
        return copy.deepcopy(scenario)
    return None
